### ISSUE TITLE
Tests failing locally

### ISSUE THREAD

**Issue by mikelehen** [mckoss/racetrack#23]
Not sure if this is just something on my end, but I'm getting an error (see below).

It also seems like not all of the tests are running.  In particular, the "Racers" suite isn't showing up.

Any ideas? Else I can try to dig into it more...

```
╰─$ npm run test

> racetrack@1.0.0 test
> tools/run-tests

Starting web server...
Testing...
Racetrack tests can only be run in a browser environment


  Headless browser tests
Listening to the page console...
Race finished in 14 steps.
    1) Run browser tests.

  Points
    ✔ linePoints: one-point
    ✔ linePoints: one-point (reversed)
    ✔ linePoints: one-point (reflected)
    ✔ linePoints: one-point (mirror-origin)
    ✔ linePoints: one-point (mirror-x)
    ✔ linePoints: horizontal
    ✔ linePoints: horizontal (reversed)
    ✔ linePoints: horizontal (reflected)
    ✔ linePoints: horizontal (mirror-origin)
    ✔ linePoints: horizontal (mirror-x)
    ✔ linePoints: vertical
    ✔ linePoints: vertical (reversed)
    ✔ linePoints: vertical (reflected)
    ✔ linePoints: vertical (mirror-origin)
    ✔ linePoints: vertical (mirror-x)
    ✔ linePoints: diagonal
    ✔ linePoints: diagonal (reversed)
    ✔ linePoints: diagonal (reflected)
    ✔ linePoints: diagonal (mirror-origin)
    ✔ linePoints: diagonal (mirror-x)
    ✔ linePoints: scaled-grid
    ✔ linePoints: scaled-grid (reversed)
    ✔ linePoints: scaled-grid (reflected)
    ✔ linePoints: scaled-grid (mirror-origin)
    ✔ linePoints: scaled-grid (mirror-x)
    ✔ linePoints: scaled-grid-rounded
    ✔ linePoints: scaled-grid-rounded (reversed)
    ✔ linePoints: scaled-grid-rounded (reflected)
    ✔ linePoints: scaled-grid-rounded (mirror-origin)
    ✔ linePoints: scaled-grid-rounded (mirror-x)
    ✔ linePoints: low-angle
    ✔ linePoints: low-angle (reversed)
    ✔ linePoints: low-angle (reflected)
    ✔ linePoints: low-angle (mirror-origin)
    ✔ linePoints: low-angle (mirror-x)


  35 passing (555ms)
  1 failing

  1) Headless browser tests
       Run browser tests.:
     Evaluation failed: Error: Mocha instance is already disposed, cannot start a new test run. Please create a new mocha instance. Be sure to set disable `cleanReferencesAfterRun` when you want to reuse the same mocha instance for multiple test runs.
    at createMochaInstanceAlreadyDisposedError (http://localhost:8080/test/mocha.js:12582:15)
    at Mocha._guardRunningStateTransition (http://localhost:8080/test/mocha.js:20004:13)
    at Mocha.run (http://localhost:8080/test/mocha.js:20053:10)
    at mocha.run (http://localhost:8080/test/mocha.js:20590:32)
    at pptr://__puppeteer_evaluation_script__:2:34
  Error: Evaluation failed: Error: Mocha instance is already disposed, cannot start a new test run. Please create a new mocha instance. Be sure to set disable `cleanReferencesAfterRun` when you want to reuse the same mocha instance for multiple test runs.
      at pptr://__puppeteer_evaluation_script__:2:34
      at ExecutionContext._ExecutionContext_evaluate (file:///Users/mikelehen/src/racetrack/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:251:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async ExecutionContext.evaluate (file:///Users/mikelehen/src/racetrack/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:140:16)
      at async Context.<anonymous> (file:///Users/mikelehen/src/racetrack/public/scripts/tests/test-in-browser.js:29:29)



Stopping web server...
```

**Comment by mckoss** [comment]
How is it now?  I rearchitected the tests yesterday.  Let me know if you're still seeing failures.

**Comment by mikelehen** [comment]
So I think this may have been user error.  I was just running `npm run test` without running `npm run build` first.  I also had some stale files in public/.  After wiping everything, doing an `npm install && npm run build && npm run test` the tests all ran (unlike before), except I hit the 10s timeout in src/tests/test-in-browser.ts.  Subsequent runs passed (in ~7s according to mocha). 

So I think the tests are working, though the timeout may be a bit sensitive.

**Comment by mckoss** [comment]
Got it.  It would be more sanitary to wipe the public/scripts directory between builds.  I'll add that.
